### ISSUE TITLE
Type Error: cannot read 'length' of undefined.

### ISSUE THREAD

**Issue by PlayMa256** [mysticatea/eslint-plugin-es#7]
**Tell us about your environment**

* **ESLint Version: 5.1.0** 
* **Node Version: 8.11.3**
* **npm Version: 6.1.0**
* **yarn Version: 1.7.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

module.exports = {
	"parser": "babel-eslint",
	"root": true,
	"plugins": [
		"node",
		"flowtype"
	],
	"extends": ["eslint:recommended", "plugin:node/recommended"],
	"env": {
		"node": true,
		"es6": true,
		"jest": true
	},
	"parserOptions": { "ecmaVersion": 2017, "sourceType": "module"},
	"rules": {
		"no-useless-escape": "off",
		"quote-props": ["error", "as-needed"],
		"no-dupe-keys": "error",
		"quotes": ["error", "double"],
		"no-undef": "error",
		"no-extra-semi": "error",
		"semi": "error",
		"no-template-curly-in-string": "error",
		"no-caller": "error",
		"yoda": "error",
		"eqeqeq": "error",
		"global-require": "off",
		"brace-style": "error",
		"key-spacing": "error",
		"space-in-parens": ["error", "never"],
		"space-infix-ops": "error",
		"indent": ["error", "tab", { "SwitchCase": 1 }],
		"no-extra-bind": "warn",
		"no-empty": "off",
		"no-multiple-empty-lines": "error",
		"no-multi-spaces": "error",
		"no-process-exit": "off",
		"no-trailing-spaces": "error",
		"no-use-before-define": "off",
		"no-unused-vars": ["error", { "args": "none" }],
		"no-unsafe-negation": "error",
		"no-loop-func": "warn",
		"space-before-function-paren": ["error", "never"],
		"space-before-blocks": "error",
		"object-curly-spacing": ["error", "always"],
		"object-curly-newline": ["error", { "consistent": true }],
		"keyword-spacing": ["error", {
			"after": true,
			"overrides": {
				"const": { "after": true },
				"try": { "after": true },
				"throw": { "after": true },
				"case": { "after": true },
				"return": { "after": true },
				"finally": { "after": true },
				"do": { "after": true }
			}
		}],
		"no-console": "off",
		"valid-jsdoc": "error",
		"node/no-unsupported-features": 'off',
		"node/no-deprecated-api": "error",
		"node/no-missing-import": "error",
		"node/no-extraneous-require": ["error"],
		"eol-last": ["error", "always"],
		"newline-per-chained-call": "off",
		"node/process-exit-as-throw": "error"
	},
	"settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash
eslint src/
```

**What did you expect to happen?**
Throw eslint errors or succeed.

**What actually happened? Please include the actual, raw output from ESLint.**

I see this error:
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at :function (project/node_modules/eslint-plugin-es/lib/rules/no-trailing-function-commas.js:30:44)
    at listeners.(anonymous function).forEach.listener (project/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (project/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (project/node_modules/eslint/lib/util/node-event-generator.js:278:22)
    at NodeEventGenerator.enterNode (project/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (project/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (project/node_modules/eslint/lib/linter.js:861:28)
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.
```

Since the error was thrown by this package, i thought it would be better to post it here other than on eslint, if it is better to be there, just let me know than i will move it.

Thanks.

**Comment by mysticatea** [comment]
Thank you for this issue.

It looks at [lib/rules/no-trailing-function-commas.js#L30](https://github.com/mysticatea/eslint-plugin-es/blob/9ce38bb0529875e1d11c3335101071ae011f088c/lib/rules/no-trailing-function-commas.js#L30).

I don't think it's a bug of this plugin because [ESTree specification](https://github.com/estree/estree/blob/df2290b23a652e1ec354b6775459a3b42e22f108/es5.md#functions) defines `Function#params` as an array. I suspect `babel-eslint` generates wrong AST.

**Comment by mysticatea** [comment]
Please open an issue on [babel-eslint](https://github.com/babel/babel-eslint).
`babel-eslint` and `eslint` are maintained by the different team.
